// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcvpplirhefxmlrgcqmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjdnBwbGlyaGVmeG1scmdjcW1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NDk3ODIsImV4cCI6MjA2ODIyNTc4Mn0.BgsH8xDm1HB8sU76J5LVGRDGxtRhdRwb2arAtYGdsek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});